#!/usr/bin/env python

import os
from os.path import isdir, join, expanduser, islink, isfile
import re
import sys
from glob import glob
from subprocess import call

dotfiles = expanduser('~/Projects/github.com/NoUseFreak/dotfiles')
homedir = expanduser('~')


print 'Installing symlinks'
if not isdir(homedir):
    os.mkdir(homedir)

for source in glob(dotfiles+'/*/*.symlink'):
    regex = re.compile('[^\/]+\/(.*)\.symlink')
    dest = expanduser(homedir+'/.'+regex.match(source.replace(dotfiles+'/', '')).group(1))
    print ' - '+source
    print '   > '+dest

    if isfile(dest) or isdir(dest):
        if not islink(dest):
            print 'ERR: '+dest+' need to be backuped first.'
            sys.exit(1)
        os.unlink(dest)

    os.symlink(source, dest)

if not isdir(homedir+'/.config'):
    os.mkdir(homedir+'/.config')
for source in glob(dotfiles+'/*/*.configsymlink'):
    regex = re.compile('[^\/]+\/(.*)\.configsymlink')
    dest = expanduser(homedir+'/.config/'+regex.match(source.replace(dotfiles+'/', '')).group(1))
    print ' - '+source
    print '   > '+dest

    if isfile(dest) or isdir(dest):
        if not islink(dest):
            print 'ERR: '+dest+' need to be backuped first.'
            sys.exit(1)
        os.unlink(dest)

    os.symlink(source, dest)

dest = expanduser(homedir+'/.vim/bundle/Vundle.vim')
print 'Installing Vundle into '+dest
call('rm -rf '+dest, shell=True)
call('git clone https://github.com/VundleVim/Vundle.vim.git '+dest, shell=True)

