syntax enable
set cursorline
set number
set ruler
set showmode
set title
set laststatus=2
set nocompatible
set backspace=2
set autoread
set listchars=eol:¬,tab:>·,trail:~,extends:>,precedes:<
set list
set colorcolumn=120


" Search Highlighting
nnoremap / :set hlsearch<CR>/
nnoremap ? :set hlsearch<CR>?
nnoremap n :set hlsearch<CR>n
nnoremap N :set hlsearch<CR>N
nnoremap <CR> :noh<CR><CR>
nnoremap <leader>/ :set hlsearch!<CR>
imap jj <ESC>



" make external keypad work in terminal vim OSX!
map <Esc>Oq 1
map <Esc>Or 2
map <Esc>Os 3
map <Esc>Ot 4
map <Esc>Ou 5
map <Esc>Ov 6
map <Esc>Ow 7
map <Esc>Ox 8
map <Esc>Oy 9
map <Esc>Op 0
map <Esc>On .
map <Esc>OQ /
map <Esc>OR *
map <kPlus> +
map <Esc>OS -
map <Esc>OM <CR>
map! <Esc>Oq 1
map! <Esc>Or 2
map! <Esc>Os 3
map! <Esc>Ot 4
map! <Esc>Ou 5
map! <Esc>Ov 6
map! <Esc>Ow 7
map! <Esc>Ox 8
map! <Esc>Oy 9
map! <Esc>Op 0
map! <Esc>On .
map! <Esc>OQ /
map! <Esc>OR *
map! <kPlus> +
map! <Esc>OS -
map! <Esc>OM <CR>

" Tab to cycle window focus
map <Tab> <C-W>W

"set runtimepath^=~/.vim/bundle/ctrlp.vim

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'


" Command bar/info strip
" https://github.com/bling/vim-airline
Plugin 'bling/vim-airline'


" List buffers in command bar
" https://github.com/bling/vim-bufferline
Plugin 'bling/vim-bufferline'

"Plugin 'ctrlpvim/ctrlp.vim'


" File tree explorer
" https://github.com/scrooloose/nerdtree
Plugin 'scrooloose/nerdtree'
Bundle 'jistr/vim-nerdtree-tabs'

" Toggle nerdtree via CTRL n
map <C-n> :NERDTreeTabsToggle<CR>
map <C-l> :tabn<CR>
map <C-h> :tabp<CR>
let g:nerdtree_tabs_synchronize_view = 1
let NERDTreeIgnore = ['\.pyc$']

Plugin 'tomtom/tcomment_vim'

" tmux statusline
" https://github.com/edkolev/tmuxline.vim
Plugin 'edkolev/tmuxline.vim'

" Unity
" -------------------------


" Better movement between files?
" https://github.com/Shougo/unite.vim
Plugin 'Shougo/unite.vim'

nnoremap <C-p> :Unite file_rec/async<cr>


" vimproc required to grep via unite
" WARNING: needs to be compiled via `make`
" https://github.com/Shougo/vimproc.vim
Plugin 'Shougo/vimproc.vim'

" Allow unity to search to Recent Used files
" https://github.com/Shougo/neomru.vim
Plugin 'Shougo/neomru.vim'

Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'airblade/vim-gitgutter'
Plugin 'tomasr/molokai'

Plugin 'davidhalter/jedi-vim'
Plugin 'Yggdroot/indentLine'
Plugin 'editorconfig/editorconfig-vim'

Bundle 'chase/vim-ansible-yaml'
Plugin 'hashivim/vim-terraform'

" away?
"Plugin 'valloric/youcompleteme'


call vundle#end()            " required
filetype plugin indent on    " required


set number
syntax enable
let g:solarized_termcolors = 256
colorscheme molokai
" let g:molokai_original = 1
let g:rehash256 = 1
set background=dark


" Tab and spacing settings
" set tabstop=4 shiftwidth=4 expandtab

" Smartcase by default (only case sensitive when Caps are inclused)
" for Case sensitive search by /helloworld\C
" note: /helloworld/c would be force case insensitve in default)
set ignorecase smartcase

set autoindent

" Ctrl+c to clipboard
vmap <C-c> :w !pbcopy<CR><CR> 

" See unsaved changes
map sd :w !diff % -<cr>


let g:vim_json_syntax_conceal = 0 
nnoremap <F5> :buffers<CR>:buffer<Space>
nnoremap <F6> :registers<CR>

